sonar.projectKey=sfdc-lex_flow-apextriggers-GitHubActions
sonar.organization=sfdc-lex


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=flow-apextriggers-GitHubActions
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=force-app/main/default/

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Comma-separated paths to directories containing test source files.
sonar.apex.coverage.reportPath=apexTests/test-result-codecoverage.json

sonar.analysis.mode=publish

sonar.coverage.exclusions=**/*Test.cls
sonar.language=apex
sonar.exclusions=**/*.cmp,**/force-app/**/fflib_*.cls,**/*.yml,**/*.js,**/*.xml,**/*.css,**/*.html,**/*.woff2,**/*.woff,**/*.auradoc,**/*.svg,force-app/main/default/staticresources/**