name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
 # push:
  #  branches:
   #   - feature/**
    #paths:
     # - 'force-app/**'
  pull_request:
    branches:
      - main
      - master 
      - uat
      - sit
      - development
    paths:
    - 'force-app/**'
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🏗️ Building the application....."
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - name: Installing Salesforce CLI
        run: |
          #Insatlling Node.js to install Salesforce CLI
          npm install @salesforce/cli --global
          #Verifying Salesforce CLI version
          sf --version
      - name: Insatll Salesforce Code Analyzer
        run: |
          #Installing Salesforce Code Analyzer plugin for static code analysis
          sf plugins install code-analyzer
          #verifying Salesforce Code Analyzer plugin version
          sf plugins --core
      - name: Running static code analysis using Salesforce Code Analyzer
        run: |
          #Creating a directory to store the static code analysis reports.
          mkdir -p scanned-reports
          #Running static code analysis on the force-app directory and generating a report
          sf code-analyzer run --target "force-app" --output-file ./scanned-reports/results.html --rule-selector Recommended  


      - name: Uploading the static code analysis report as an artifact. . 
        if: always() # This ensures that the artifact is uploaded even if the previous steps fail, allowing you to review the report for debugging purposes.
        uses: actions/upload-artifact@v7.0.0  
        with:
          name: code-analysis-report
          path: scanned-reports/results.html
          if-no-files-found: ignore

      - name : Decrypting the JWT encrypted key for Authentication..
        run: |
          #Decrypting the JWT encrypted key using OpenSSL
          openssl enc -aes-256-cbc -d -in ${{secrets.JWT_ENCRYPTION_KEY_FILE}} -out ${{secrets.JWT_KEY_FILE}} -K ${{secrets.ENCRYPTION_KEY}} -iv ${{secrets.ENCRYPTION_IV}} -base64
      - name: Authenticating to Salesforce using JWT....
        run:
          #Authenticating to Salesforce using the decrypted JWT key.
          sf org login jwt --client-id ${{secrets.SF_CLIENT_ID}} --jwt-key-file ${{secrets.JWT_KEY_FILE}} --username ${{secrets.SF_USERNAME}} --instance-url ${{vars.SF_INSTANCE_URL}} --alias ${{vars.SF_ALIAS}} --set-default

      - name: Run Apex Local Test Cases..
        run: |
          mkdir -p localTestsReport
          sf apex run test --test-level RunLocalTests --code-coverage --detailed-coverage --output-dir ./localTestsReport/ --result-format human --wait 10 --synchronous --target-org ${{vars.SF_ALIAS}}
          #sf apex run test --test-level RunLocalTests --code-coverage --detailed-coverage --output-dir ./localTestsReport/ --result-format human --wait 10 --synchronous

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          flags: Apex
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Validating to Salesforce organization
        run: |
          #Validating the Salesforce organization by displaying the authenticated user
          sf project deploy start --target-org ${{vars.SF_ALIAS}} --source-dir force-app --dry-run --wait 10
      - name: Deploying to Salesforce organization
        run: |
          #Deploying to Salesforce organization
          sf project deploy start --target-org ${{vars.SF_ALIAS}} --source-dir force-app --ignore-conflicts --wait 10
         
