name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🏗️ Building the application..."
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - name: Installing Salesforce CLI
        run: |
          #Insatlling Node.js to install Salesforce CLI
          npm install @salesforce/cli --global
          sf --version
      


    